### ISSUE TITLE
Desain 3D

### ISSUE THREAD

**Issue by Renoadith** [Renoadith/Projek-Mikrokontroller#10]

**Comment by aglvga** [comment]
![finish](https://github.com/Renoadith/Projek-Mikrokontroller/assets/169014774/eff73d30-c806-4158-b1f0-ac99551e6c77)
![tmpk depan](https://github.com/Renoadith/Projek-Mikrokontroller/assets/169014774/8a13f006-5be6-4a79-b682-0db8b17f1307)
![tmpk smpng](https://github.com/Renoadith/Projek-Mikrokontroller/assets/169014774/af84c8c8-1f3f-4f47-9fcc-4ff099e8cd25)

**Comment by krisnawijaya2502** [comment]
![Blue Modern Audio Speaker Desktop Prototype (1)](https://github.com/Renoadith/Projek-Mikrokontroller/assets/134272498/2fa84ba8-6103-4c62-a92f-56e5ae7fe2d6)

**Comment by aglvga** [comment]
![Uploading finish 1.png…]()

**Comment by aglvga** [comment]
![finish 1](https://github.com/Renoadith/Projek-Mikrokontroller/assets/169014774/63843e9f-e7e7-4160-9af8-0518c723c836)
