### ISSUE TITLE
Pengumpulan Semua Komponen

### ISSUE THREAD

**Issue by Renoadith** [Renoadith/Projek-Mikrokontroller#12]

**Comment by Labibfa** [comment]
arduino

**Comment by Labibfa** [comment]
dari jurnal rancang bangun alat pendeteksi dan pemberi peringatan kebisingan suara berbasis arduino

Hardware : Oled 128x64, sensor suara MAX4466, adaptor 9v/1A, speaker subwoofer, mp3 player YX5300, micro sd card, arduino uno 

Software : arduino ide, microsoft visio, fritzing, audacity

alat : solder, timah solder, kabel jumper, kabel usb a to usb b, obeng

**Comment by anggerbmw7** [comment]
adaptor sebagai sumber listrik
