### ISSUE TITLE
Perancangan Sistem

### ISSUE THREAD

**Issue by Renoadith** [Renoadith/Projek-Mikrokontroller#14]

**Comment by Renoadith** [comment]
tes

**Comment by Labibfa** [comment]
jurnal Rancang Bangun Alat Pendeteksi dan Pemberi Peringatan Kebisingan Suara Berbasis Arduino
![Screenshot (406)](https://github.com/Renoadith/Projek-Mikrokontroller/assets/168981880/568ee9ec-1b3d-46a1-8da9-1bfe3590efc5)

**Comment by Labibfa** [comment]
![Screenshot (407)](https://github.com/Renoadith/Projek-Mikrokontroller/assets/168981880/ea393bff-a322-42ad-8b69-6ad4ff9bf341)
![Screenshot (408)](https://github.com/Renoadith/Projek-Mikrokontroller/assets/168981880/13a01aaa-c346-426c-ad29-95e14cbdffaf)

**Comment by Renoadith** [comment]
![image](https://github.com/Renoadith/Projek-Mikrokontroller/assets/168974067/2359a884-3b89-4f68-bac8-df6837540f50)
