### ISSUE TITLE
Riset Komponen + Membeli

### ISSUE THREAD

**Issue by Renoadith** [Renoadith/Projek-Mikrokontroller#17]
- Lak iso info harga + nggon tukune ya
- Masalah tukue gampang isok dibuck up ambek lianne
- Komponen e ditambahi modul amplifier yo

**Comment by rhmputri** [comment]
![IMG20240524234516 (1)](https://github.com/Renoadith/Projek-Mikrokontroller/assets/168979944/1b45c8dd-c293-4c40-a764-dd1ea6921e0d)
