### ISSUE TITLE
Revisi Desain 3D

### ISSUE THREAD

**Issue by Renoadith** [Renoadith/Projek-Mikrokontroller#18]
- Revisi ya ditambahi keterangan komponen opo ae cuman dikei inisial ae koyok Arduino ditulis A, Speaker ditulis B, dst
- Ambek perkiraan ukuranne sekalian yaw
- Komponen e ditambaho modul amplifier

![Gambar 3 4 Desain gambar kerja tiga dimensi proses sub-assembly](https://github.com/Renoadith/Projek-Mikrokontroller/assets/168974067/996b1a26-240c-40a2-a593-1a05a8eb1489)

**Comment by rhmputri** [comment]
![dalam](https://github.com/Renoadith/Projek-Mikrokontroller/assets/168979944/8ed2ad29-9bdc-4e39-876b-9954aa62deeb)
![luar](https://github.com/Renoadith/Projek-Mikrokontroller/assets/168979944/e9e88064-d7b3-4960-a211-9ffae7ceba4b)

**Comment by rhmputri** [comment]
[ukuran bagian dalam.pdf](https://github.com/Renoadith/Projek-Mikrokontroller/files/15383994/ukuran.bagian.dalam.pdf)

**Comment by Renoadith** [comment]
![ukuran bagian dalam_page-0001](https://github.com/Renoadith/Projek-Mikrokontroller/assets/168974067/0e12cc31-caef-4ce4-a8ec-31d118e87633)

**Comment by rhmputri** [comment]
![tampak dalam](https://github.com/Renoadith/Projek-Mikrokontroller/assets/168979944/85a7ba89-321d-4ff1-a367-43d0feff3b33)
![tampak luar](https://github.com/Renoadith/Projek-Mikrokontroller/assets/168979944/3f1941e4-73e7-47b8-a253-5c22787e46cd)
[ukuran tampak dalam.pdf](https://github.com/Renoadith/Projek-Mikrokontroller/files/15455995/ukuran.tampak.dalam.pdf)
[ukuran tampak luar.pdf](https://github.com/Renoadith/Projek-Mikrokontroller/files/15455997/ukuran.tampak.luar.pdf)

**Comment by rhmputri** [comment]
![ukuran tampak luar_page-0001](https://github.com/Renoadith/Projek-Mikrokontroller/assets/168979944/ec05c7ae-f840-4222-9692-bf013c5a8df7)
![ukuran tampak dalam_page-0001](https://github.com/Renoadith/Projek-Mikrokontroller/assets/168979944/3da72351-e29d-472a-8b1f-c3a4b2bfbd89)

**Comment by rhmputri** [comment]
![BAGIAN DALAM](https://github.com/Renoadith/Projek-Mikrokontroller/assets/168979944/a25a9c53-3324-40b0-a35b-9acb642eea06)
![BAGIAN LUAR](https://github.com/Renoadith/Projek-Mikrokontroller/assets/168979944/49b72631-4169-4363-a4f5-2f5868484604)
![BAGIAN LUAR_page-0001](https://github.com/Renoadith/Projek-Mikrokontroller/assets/168979944/0af3ba8b-6d2c-47d8-b7cf-e3afe879404c)

**Comment by rhmputri** [comment]
![BAGIAN DALAM_page-0001](https://github.com/Renoadith/Projek-Mikrokontroller/assets/168979944/ee1e3859-b8b6-4b1e-9edf-ab9528a42f78)
